### ISSUE TITLE
New Data: Not sure where to save it

### ISSUE THREAD

**Issue by chrisd31** [segurita/gui#3]
Just parsed all the data from [BVL](http://www.bvl.com.pe/empresas/datacapi.htm) and added the company's full name and url to their respective financial statements. The data is saved in a csv file which you can get from [here](https://drive.google.com/open?id=0B-BLHgK6-VrmNzdqR0RYSVpVcUU) 

I don't have experience with Django so I don't know exactly where to save this info. Also not sure if the code that generates the file should live in the project or not.

**Comment by aniversarioperu** [comment]
the data is here https://github.com/segurita/data as JSON files. I need to improve the `tests.py` to validate the new data from pull requests!
